src/carts/urls.py
from django.urls import path
from .views import increase_product_in_cart, remove_from_cart, decrease_product_in_cart, CartDetailView, AddToCartAjax


app_name = "carts"

urlpatterns = [
    path('', CartDetailView.as_view(), name='show-cart'),
    path('add/<int:product_id>/', AddToCartAjax.as_view(), name='add-to-cart'),
    path('increase/<int:product_id>/', increase_product_in_cart, name='increase-product-in-cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove-from-cart'),
    path('decrease/<int:product_id>/', decrease_product_in_cart, name='decrease-product-in-cart')
]

src/checkout/urls.py
from django.urls import path
from .views import CheckoutView, checkout_success, PaymentView, PromoCodeView


app_name = "checkout"

urlpatterns = [
    path('', CheckoutView.as_view(), name='checkout'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('success/', checkout_success, name='checkout-success'),
    path('add-promotion-code/', PromoCodeView.as_view(), name='promotion-code')
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from carts.views import OrdersListView
from carts.views import RefundView
from checkout.views import ShippingAddressUpdateView


urlpatterns = [
    path('', include('products.urls')),
    path('cart/', include('carts.urls')),
    path('checkout/', include('checkout.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/orders/', OrdersListView.as_view(), name='show-orders'),
    path('accounts/profile/', ShippingAddressUpdateView.as_view(), name='profile'),
    path('refund/', RefundView.as_view(), name='refund')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path
from .views import HomePage
from .views import ProductDetailView


app_name = "products"

urlpatterns = [
    path('', HomePage.as_view(), name='home-page'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail')
]

src/carts/models.py
from django.db import models
from django.conf import settings
from django import forms

from products.models import Product
from checkout.models import ShippingAddress
from checkout.models import Payment


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.item.name}: {self.quantity}'

    def get_total(self):
        return round(self.item.price * self.quantity, 2)


class Order(models.Model):
    order_id = models.CharField(max_length=20)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    ordered = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress, on_delete=models.SET_NULL, null=True, blank=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, null=True, blank=True)
    promo_code_applied = models.BooleanField(default=False)
    promo_code_discount = models.FloatField(default=0)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username}: {self.get_all_items()}'

    def get_all_items(self):
        return [item for item in self.items.all()]

    def get_total_amount(self):
        total = sum(item.get_total() for item in self.items.all())
        return total - self.promo_code_discount

    def get_total_quantity(self):
        return sum(item.quantity for item in self.items.all())


class Refund(models.Model):
    reason = models.TextField()
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    granted = models.BooleanField(default=False)

    def __str__(self):
        return f'Refund for order {self.order.order_id}'


class RefundForm(forms.ModelForm):
    order_id = forms.CharField()

    class Meta:
        model = Refund
        fields = ['order_id', 'reason']

src/carts/views.py
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.decorators  import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import FormView
from django.http import JsonResponse

from products.models import Product
from .models import Order, OrderItem
from .models import RefundForm


class RefundView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    template_name = 'carts/refund.html'
    form_class = RefundForm
    success_url = reverse_lazy('refund')
    success_message = "The request for a refund has been successfully sent"

    def form_valid(self, form):
        try:
            order = Order.objects.get(order_id=form.cleaned_data['order_id'])
        except Order.DoesNotExist:
            messages.warning(self.request, "Provided order id does not exists")
            return redirect('refund')
        order.refund_requested = True
        order.save()
        form.instance.user = self.request.user
        form.instance.order = order
        return super().form_valid(form)


class OrdersListView(LoginRequiredMixin, ListView):
    context_object_name = 'orders'

    def get_queryset(self):
        return self.request.user.order_set.filter(ordered=True)


class CartDetailView(LoginRequiredMixin, DetailView):
    context_object_name = 'order'
    template_name = 'carts/cart.html'

    def get_object(self, queryset=None):
        return self.request.user.order_set.filter(ordered=False).first()


class AddToCartAjax(View):
    def post(self, request, product_id, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return JsonResponse({
                'error': 'In order to add item to cart please create an account'
            }, status=401)
        if self.request.is_ajax:
            product = get_object_or_404(Product, pk=product_id)
            order, _ = Order.objects.get_or_create(user=self.request.user, ordered=False)
            if order.items.filter(item__pk=product_id).exists():
                order_item = order.items.get(item__pk=product_id)
                order_item.quantity += 1
                order_item.save()
            else:
                order_item = OrderItem.objects.create(user=self.request.user, item=product)
                order.items.add(order_item)
            return JsonResponse({
                'msg': "Product has been successfully added to cart",
                'quantity': order_item.quantity,
                'total_items': order.get_total_quantity()
            })


@login_required
def increase_product_in_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    order, _ = Order.objects.get_or_create(user=request.user, ordered=False)
    if order.items.filter(item__pk=product_id).exists():
        order_item = order.items.get(item__pk=product_id)
        order_item.quantity += 1
        order_item.save()
    else:
        order.items.create(user=request.user, item=product)
    messages.success(request, 'Product has been added to cart.')
    return redirect('carts:show-cart')


@login_required
def decrease_product_in_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    order = Order.objects.filter(user=request.user, ordered=False).first()
    if order:
        order_item = order.items.filter(user=request.user, item=product).first()
        if order_item:
            order_item.quantity -= 1
            order_item.save()
            if order_item.quantity <= 0:
                order.items.remove(order_item)
            messages.success(request, 'Product has been removed from cart.')
        else:
            messages.warning(request, 'This item is not in your cart.')
    else:
        messages.warning(request, 'Cart does not exists. Add some products to cart.')
        return redirect('products:home-page')
    return redirect('carts:show-cart')


@login_required
def remove_from_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    order = Order.objects.filter(user=request.user, ordered=False).first()
    if order:
        order_item = order.items.filter(user=request.user, item=product).first()
        if order_item:
            order.items.remove(order_item)
            messages.success(request, 'Product has been removed from cart.')
        else:
            messages.warning(request, 'This item is not in your cart.')
    else:
        messages.warning(request, 'Cart does not exists. First add products to cart.')
        return redirect('products:home-page')
    return redirect('carts:show-cart')

src/carts/templates/carts/cart.html
{% extends "products/base.html" %}
{% load static %}
{% block content %}
    <div class="container my-4">
        <h2 class="text-center my-4">Your Cart</h2>
        {% include "products/messages.html" %}
        <table class="table">
            {% if order.items.all %}
            <thead>
                <tr>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col" class="text-center">Amount</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            {% endif %}
            <tbody>
                {% for item in order.items.all %}
                    <tr>
                        <td>{{ item.item.name }}</td>
                        <td>
                            <a href="{% url 'carts:decrease-product-in-cart' item.item.id %}"><span class="badge badge-dark mr-2"><i class="fas fa-minus"></i></span></a>
                            <span>{{ item.quantity }}</span>
                            <a href="{% url 'carts:increase-product-in-cart' item.item.id %}"><span class="badge badge-dark ml-2"><i class="fas fa-plus"></i></span></a>
                        </td>
                        <td>{{ item.item.price|floatformat:2 }} $</td>
                        <td class="text-center">{{ item.get_total|floatformat:2 }} $</td>
                        <td class="text-right">
                            <a class="btn btn-danger" href="{% url 'carts:remove-from-cart' item.item.id %}"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                {% empty %}
                    <div class="alert alert-info" role="alert">
                        The cart is empty
                    </div>
                {% endfor %}
                {% if order.promo_code_applied %}
                    <tr>
                        <td colspan="3"></td>
                        <td class="text-center text-success">
                            Discount: <span class="font-weight-bold">-{{ order.promo_code_discount|floatformat:2 }} $</span>
                        </td>
                    </tr>
                {% endif %}
                <tr>
                    <td colspan="3">
                        <a class="btn btn-warning" href="{% url 'products:home-page' %}">Back to Home Page</a>
                    </td>
                    {% if order.items.all %}
                    <td class="text-center">
                        Total: <span class="font-weight-bold ml-1">{{ order.get_total_amount|floatformat:2 }} $</span>
                    </td>
                    <td>
                        <a class="btn btn-info btn-block" href="{% url 'checkout:checkout' %}">Checkout</a>
                    </td>
                    {% endif %}
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

src/carts/templates/carts/order_list.html
{% extends "products/base.html" %}
{% block content %}
    <div class="container my-4">
        <h2 class="text-center my-4">Your Orders</h2>
        {% include "products/messages.html" %}
        <table class="table">
            {% if orders %}
                <thead>
                    <tr>
                        <th scope="col">Order ID</th>
                        <th scope="col">Pay date</th>
                        <th scope="col">Products</th>
                    </tr>
                </thead>
            {% endif %}
            <tbody>
                {% for order in orders %}
                    <tr>
                        <th scope="row">{{ order.order_id }}</th>
                        <td>
                            {{ order.payment.issued_data }}
                        </td>
                        <td>
                            {% for item in order.items.all %}
                                <div class="row align-middle">
                                    <div class="col-6 mb-3">
                                        <h6>{{ item.item.name }}</h6>
                                        <small>Quantity: {{ item.quantity }}</small>
                                    </div>
                                    <div class="col-6 text-right">
                                        <span class="font-weight-bold mr-4">{{ item.get_total|floatformat:2 }} $</span>
                                    </div>
                                </div>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="text-right"><small>Shipping Address:</small></td>
                        <td>
                            <small >
                                {{ order.shipping_address.first_name }} {{ order.shipping_address.last_name }} <br>
                                {{ order.shipping_address.street }} {{ order.shipping_address.street_number }} <br>
                                {{ order.shipping_address.zip_code }} <br>
                                {{ order.shipping_address.country }}
                            </small >
                        </td>
                    </tr>
                    {% if order.promo_code_applied %}
                        <tr class="">
                            <td colspan="3" class="text-right">Discount: <span class="font-weight-bold">-{{ order.promo_code_discount|floatformat:2 }} $</span></td>
                        </tr>
                    {% endif %}
                    <tr class="table-success">
                        <td colspan="3" class="text-right text-success"><h5>Total: <span class="font-weight-bold">{{ order.get_total_amount|floatformat:2 }} $</span></h5></td>
                    </tr>
                    {% empty %}
                        <div class="alert alert-info" role="alert">
                            You do not have any orders
                        </div>
                {% endfor %}
                <tr>
                    <td colspan="3"><a class="btn btn-warning" href="{% url 'products:home-page' %}">Back to Home Page</a> </td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

src/carts/templates/carts/refund.html
{% extends "products/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container my-4">
        <h2 class="text-center my-4">Refund</h2>
        {% include "products/messages.html" %}
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-block btn-success my-4">Send a refund request</button>
        </form>
    </div>
{% endblock %}