src/carts/urls.py
from django.urls import path
from .views import increase_product_in_cart, remove_from_cart, decrease_product_in_cart, CartDetailView, AddToCartAjax


app_name = "carts"

urlpatterns = [
    path('', CartDetailView.as_view(), name='show-cart'),
    path('add/<int:product_id>/', AddToCartAjax.as_view(), name='add-to-cart'),
    path('increase/<int:product_id>/', increase_product_in_cart, name='increase-product-in-cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove-from-cart'),
    path('decrease/<int:product_id>/', decrease_product_in_cart, name='decrease-product-in-cart')
]

src/checkout/urls.py
from django.urls import path
from .views import CheckoutView, checkout_success, PaymentView, PromoCodeView


app_name = "checkout"

urlpatterns = [
    path('', CheckoutView.as_view(), name='checkout'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('success/', checkout_success, name='checkout-success'),
    path('add-promotion-code/', PromoCodeView.as_view(), name='promotion-code')
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from carts.views import OrdersListView
from carts.views import RefundView
from checkout.views import ShippingAddressUpdateView


urlpatterns = [
    path('', include('products.urls')),
    path('cart/', include('carts.urls')),
    path('checkout/', include('checkout.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/orders/', OrdersListView.as_view(), name='show-orders'),
    path('accounts/profile/', ShippingAddressUpdateView.as_view(), name='profile'),
    path('refund/', RefundView.as_view(), name='refund')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path
from .views import HomePage
from .views import ProductDetailView


app_name = "products"

urlpatterns = [
    path('', HomePage.as_view(), name='home-page'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail')
]

src/checkout/models.py
from django.db import models
from django import forms
from django_countries.fields import CountryField
from django.urls import reverse
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


class ShippingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    street_number = models.CharField(max_length=10)
    zip_code = models.CharField(max_length=30)
    city = models.CharField(max_length=50)
    country = CountryField()
    phone = models.CharField(max_length=30)
    current_address = models.BooleanField(default=False)

    def __str__(self):
        return f'Shipping address for {self.user.username}: {self.street} {self.street_number}, {self.city}'

    def get_absolute_url(self):
        return reverse('profile')


class ShippingAddressForm(forms.ModelForm):
    save_address = forms.BooleanField(required=False, label='Save the billing addres')

    class Meta:
        model = ShippingAddress
        fields = [
            'first_name',
            'last_name',
            'street',
            'street_number',
            'zip_code',
            'city',
            'country',
            'phone'
        ]


class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    stripe_id = models.CharField(max_length=60)
    amount = models.FloatField()
    issued_data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} payment: {self.amount}'


class PromotionCode(models.Model):
    code = models.CharField(max_length=50)
    percentage_discount = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(1.0)])

    def __str__(self):
        return self.code


class PromotionCodeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['code'].required = False

    class Meta:
        model = PromotionCode
        fields = ['code']
        labels = {
            'code': 'Promotion Code'
        }

src/checkout/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import UpdateView, View
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.crypto import get_random_string

from carts.models import Order
from .models import ShippingAddressForm
from .models import PromotionCodeForm
from .models import PromotionCode
from .models import ShippingAddress
from .models import Payment

import stripe


stripe.api_key = settings.STRIPE_SECRET_KEY


class CheckoutView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        order = Order.objects.filter(user=self.request.user, ordered=False).first()
        if not order:
            return redirect('checkout:checkout')
        order_items = order.get_all_items()
        shipping_address = ShippingAddress.objects.filter(user=self.request.user, current_address=True)
        shipping_address = shipping_address.first() if shipping_address.exists() else None
        form = ShippingAddressForm(instance=shipping_address)
        promo_form = PromotionCodeForm()
        context = {
            'order': order,
            'order_items': order_items,
            'form': form,
            'promo_form': promo_form
        }
        return render(self.request, 'checkout/checkout.html', context)

    def post(self, *args, **kwargs):
        form = ShippingAddressForm(self.request.POST)
        if form.is_valid():
            shipping_address = form.save(commit=False)
            shipping_address.user = self.request.user
            shipping_address.save()
            order = Order.objects.filter(user=self.request.user, ordered=False).first()
            order.shipping_address = shipping_address
            order.save()
            if form.cleaned_data['save_address']:
                current_shipping_address = ShippingAddress.objects.filter(user=self.request.user, current_address=True).first()
                if current_shipping_address:
                    current_shipping_address.current_address = False
                    current_shipping_address.save()
                shipping_address.pk = None
                shipping_address.current_address = True
                shipping_address.save()
        return redirect('checkout:payment')


class PaymentView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        order = Order.objects.filter(user=self.request.user, ordered=False).first()
        return render(self.request, 'checkout/payment.html', {'order': order})

    def post(self, *args, **kwargs):
        order = Order.objects.filter(user=self.request.user, ordered=False).first()
        token = self.request.POST.get('stripeToken')
        try:
            charge = stripe.Charge.create(
              amount=round(float(order.get_total_amount() * 100)),
              currency="usd",
              source=token
            )
        except stripe.error.CardError:
            messages.error(self.request, 'Payment could not be made')
            return redirect('products:home-page')
        except Exception:
            messages.error(self.request, 'Internal server error')
            return redirect('products:home-page')

        payment = Payment(
            user=self.request.user,
            stripe_id=charge.id,
            amount=order.get_total_amount()
        )
        payment.save()
        order.order_id = get_random_string(length=20)
        order.payment = payment
        order.ordered = True
        order.save()

        messages.info(self.request, 'Payment was successfully issued')
        return redirect('checkout:checkout-success')


class ShippingAddressUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    form_class = ShippingAddressForm
    template_name = 'checkout/profile.html'
    success_message = "The address has been successfully updated"

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.current_address = True
        return super().form_valid(form)

    def get_object(self):
        obj = ShippingAddress.objects.filter(user=self.request.user, current_address=True)
        return obj.first() if obj.exists() else None


class PromoCodeView(LoginRequiredMixin, View):
    def post(self, *args, **kwargs):
            form = PromotionCodeForm(self.request.POST)
            if form.is_valid():
                order = Order.objects.filter(user=self.request.user, ordered=False).first()
                if order.promo_code_applied:
                    messages.warning(self.request, "The promotion code has been already applied")
                    return redirect('checkout:checkout')
                try:
                    code = PromotionCode.objects.get(code=form.cleaned_data.get('code'))
                except PromotionCode.DoesNotExist:
                    messages.warning(self.request, "Provided code does not exists")
                    return redirect('checkout:checkout')
                order.promo_code_discount = order.get_total_amount() * code.percentage_discount
                order.promo_code_applied = True
                order.save()
                return redirect('checkout:checkout')


def checkout_success(request):
    return render(request, 'checkout/success.html')

src/checkout/templates/checkout/checkout.html
{% extends "products/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container my-4">
        <h2 class="text-center my-4">Checkout</h2>
        {% include "products/messages.html" %}
        {% if order_items %}
            <div class="row">
                <div class="col-lg-8 order-2 order-lg-1">
                    <div class="card">
                      <div class="card-body">
                        <h5 class="card-title">Shipping Address</h5>
                          <form method="POST">
                              {% csrf_token %}
                              {% include 'checkout/shipping_address_form.html' %}
                              <div class="form-group col-md-4">
                                {{ form.save_address|as_crispy_field  }}
                            </div>
                              <button type="submit" class="btn btn-block btn-success my-4">Pay for the Order</button>
                          </form>
                      </div>
                    </div>
                </div>
                <div class="col-lg-4 order-1 order-lg-2">
                    <div class="card">
                      <div class="card-body">
                        <h5 class="card-title mb-4">Your order</h5>
                          <ul class="list-group">
                            {% for item in order_items %}
                                <li class="list-group-item d-flex justify-content-between">
                                    <div>
                                        <h6 class="font-weight-bold">{{ item.item.name }}</h6>
                                        <small>Quantity: {{ item.quantity }}</small>
                                    </div>
                                    <span>{{ item.get_total|floatformat:2 }} $</span>
                                </li>
                            {% endfor %}
                                {% if order.promo_code_applied %}
                                    <li class="list-group-item d-flex justify-content-between">
                                    <span class="text-success">Discount</span>
                                    <span class="font-weight-bold text-success">-{{ order.promo_code_discount|floatformat:2 }} $</span>
                                </li>
                                {% endif %}
                                <li class="list-group-item d-flex justify-content-between">
                                    <h6>TOTAL:</h6>
                                    <span class="font-weight-bold text-success">{{ order.get_total_amount|floatformat:2 }} $</span>
                                </li>
                                {% if not order.promo_code_applied %}
                                    <div class="form-group">
                                        <form method="POST" action="{% url 'checkout:promotion-code' %}">
                                            {% csrf_token %}
                                            {{ promo_form.code|as_crispy_field  }}
                                            <button class="btn btn-primary btn-block">Add Code</button>
                                        </form>
                                    </div>
                                {%endif %}
                          </ul>
                      </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="alert alert-warning" role="alert">
                No items in cart.
            </div>
            <div class="m-auto w-50  py-4">
                <a class="btn btn-warning btn-block" href="{% url 'products:home-page' %}">Back to Home Page</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

src/checkout/templates/checkout/payment.html
{% extends "products/base.html" %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'checkout/stripe_payment.css' %}">
<script src="https://js.stripe.com/v3/"></script>
{% endblock %}

{% block content %}
    <div class="container my-4">
        <h2 class="text-center my-4">Payment</h2>

        <form action="{% url 'checkout:payment' %}" method="post" id="payment-form" class="p-5 bg-light">
            {% csrf_token %}
            <div class="w-100 my-3">
                <label for="card-element">Credit or debit card</label>
                <div id="card-element">
                <!-- A Stripe Element will be inserted here. -->
                </div>

                <!-- Used to display form errors. -->
                <div id="card-errors" role="alert"></div>
            </div>
            <button class="btn btn-primary btn-block">Pay {{ order.get_total_amount|floatformat:2 }} $</button>
        </form>

    </div>
{% endblock %}

{% block extra_scripts %}
<script type="text/javascript" src="{% static 'checkout/stripe_payment.js' %}"></script>
{% endblock %}

src/checkout/templates/checkout/profile.html
{% extends "products/base.html" %}
{% block content %}
    <div class="container my-4">
        {% include "products/messages.html" %}
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Shipping Address</legend>
                {% include "checkout/shipping_address_form.html" %}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Update Shipping Address</button>
            </div>
        </form>
        <a class="btn btn-warning" href="{% url 'products:home-page' %}">Back to Home Page</a>
    </div>
{% endblock %}

src/checkout/templates/checkout/shipping_address_form.html
{% load crispy_forms_tags %}
<div class="form-row">
    <div class="form-group col-md-6">
        {{ form.first_name|as_crispy_field  }}
    </div>
    <div class="form-group col-md-6">
        {{ form.last_name|as_crispy_field  }}
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-8">
        {{ form.street|as_crispy_field  }}
    </div>
    <div class="form-group col-md-4">
        {{ form.street_number|as_crispy_field  }}
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-8">
        {{ form.city|as_crispy_field  }}
    </div>
    <div class="form-group col-md-4">
        {{ form.zip_code|as_crispy_field  }}
    </div>
</div>
{{ form.country|as_crispy_field  }}
{{ form.phone|as_crispy_field  }}

src/checkout/templates/checkout/success.html
{% extends "products/base.html" %}
{% block content %}
    <div class="container my-4">
        <div class="text-center my-4">
            <h3 class="display-4 text-success">The order has been successfully proceed</h3>
            <h4>Thank you!</h4>
            <div class="m-auto w-50  py-4">
                <a class="btn btn-warning btn-block mb-3" href="{% url 'products:home-page' %}">Back to Home Page</a>
                <a class="btn btn-success btn-block" href="{% url 'show-orders' %}">Check your orders</a>
            </div>
        </div>
    </div>
{% endblock %}