src/carts/urls.py
from django.urls import path
from .views import increase_product_in_cart, remove_from_cart, decrease_product_in_cart, CartDetailView, AddToCartAjax


app_name = "carts"

urlpatterns = [
    path('', CartDetailView.as_view(), name='show-cart'),
    path('add/<int:product_id>/', AddToCartAjax.as_view(), name='add-to-cart'),
    path('increase/<int:product_id>/', increase_product_in_cart, name='increase-product-in-cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove-from-cart'),
    path('decrease/<int:product_id>/', decrease_product_in_cart, name='decrease-product-in-cart')
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from carts.views import OrdersListView
from carts.views import RefundView
from checkout.views import ShippingAddressUpdateView


urlpatterns = [
    path('', include('products.urls')),
    path('cart/', include('carts.urls')),
    path('checkout/', include('checkout.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/orders/', OrdersListView.as_view(), name='show-orders'),
    path('accounts/profile/', ShippingAddressUpdateView.as_view(), name='profile'),
    path('refund/', RefundView.as_view(), name='refund')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path
from .views import HomePage
from .views import ProductDetailView


app_name = "products"

urlpatterns = [
    path('', HomePage.as_view(), name='home-page'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail')
]

src/products/models.py
from django.db import models
from django.shortcuts import reverse
# from PIL import Image


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Product(models.Model):
    IMG_DIMENSION = 540

    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.FloatField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to='products/')

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.name

    def save(self):
        super().save()

        with Image.open(self.thumbnail.path) as img:
            if img.height > self.IMG_DIMENSION or img.width > self.IMG_DIMENSION:
                img.thumbnail((self.IMG_DIMENSION, self.IMG_DIMENSION))
                img.save(self.thumbnail.path)

    def get_product_url(self):
        return reverse("products:product-detail", kwargs={
            'pk': self.pk
        })

src/products/views.py
from django.views.generic import ListView, DetailView
from .models import Product


class HomePage(ListView):
    model = Product
    template_name = 'products/home.html'
    context_object_name = 'products'
    paginate_by = 4


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_details.html'

src/products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Django e-commerce website</title>
    {% block extra_head %} {% endblock %}
</head>
<body>
    {% include 'products/navbar.html' %}
    {% block body %}{% endblock %}
    {% block content %}{% endblock %}
    {% block extra_body %} {% endblock %}

    <footer class="p-5 bg-dark text-white text-center border-top">
        <p>Django ecommerce website by szymcio32</p>
    </footer>
    <!--Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!--Font Awesome-->
    <script src="https://kit.fontawesome.com/7235818b31.js" crossorigin="anonymous"></script>
    {% block extra_scripts %} {% endblock %}
</body>
</html>

src/products/templates/products/home.html
{% extends "products/base.html" %}
{% block content %}
    <main role="main" class="container">
        <div class="my-3 py-3 text-center">
            <h2 class="display-4">PRODUCTS</h2>
        </div>
        {% include "products/messages.html" %}
        <section class="row">
            {% for product in products %}
            <div class="col-md-3">
                <div class="card text-center border-0 mb-4">
                    <div>
                        <a href="{% url 'products:product-detail' pk=product.pk %}">
                            <img src="{{ product.thumbnail.url }}" class="card-img-top" alt="{{ product.name }}">
                        </a>
                    </div>
                    <div class="card-body">
                        <p class="card-text mb-1">{{ product.name }}</p>
                        <p class="card-text font-weight-bold">{{ product.price|floatformat:2 }} $</p>
                        <a href="{% url 'products:product-detail' pk=product.pk %}" class="btn btn-primary">View details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </section>
        <nav aria-label="Product navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous  %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% endif %}
                {% for page_num in page_obj.paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endfor %}
                {% if page_obj.has_next   %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </main>
{% endblock %}

src/products/templates/products/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

src/products/templates/products/navbar.html
{% load cart_icon %}
<nav class="navbar sticky-top navbar-expand-md navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand h1 text-primary" href="{% url 'products:home-page' %}">Django ecommerce website</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:home-page' %}">Home</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'show-orders' %}">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'refund' %}">Request Refund</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'carts:show-cart' %}">Cart<i class="fas fa-shopping-cart ml-2"></i>
                        <span id="cart-total-items" class="badge badge-info">{{ user| total_cart_items }}</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

src/products/templates/products/product_details.html
{% extends "products/base.html" %}
{% load static %}
{% block content %}
    <section id="product-container" class="container my-5">
        {% include "products/messages.html" %}
        <div id="product-details" class="card border-0">
            <div class="row">
                <div class="col-md-6">
                    <img src="{{ product.thumbnail.url }}" class="card-img-top" alt="{{ object.name }}">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h2 class="card-title">{{ object.name }}</h2>
                        <h6 class="card-subtitle mb-2 badge badge-primary">{{ object.category }}</h6>
                        <p class="card-text my-5">{{ object.description }}</p>
                        <div class="d-flex align-items-center">
                            <h5 class="card-text font-weight-bold mr-4">{{ object.price|floatformat:2 }} $</h5>
                            <button id="add_to_cart" class="btn btn-primary">
                                <i class="fas fa-shopping-cart mr-2"></i>Add to cart
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block extra_scripts %}
<script type="text/javascript" src="{% static 'products/main.js' %}"></script>
<script>
    // add event listener to 'add to cart' button
    document.querySelector('#add_to_cart').addEventListener('click', (e) => {
        e.preventDefault();

        const csrftoken = getCookie('csrftoken');

        const xhr = new XMLHttpRequest();
        xhr.open('POST', "{% url 'carts:add-to-cart' object.pk %}", true);
        xhr.setRequestHeader('X-CSRFToken', csrftoken);
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');

        var json_response;
        xhr.onload = () => {
            if (xhr.status == 200){
                json_response = JSON.parse(xhr.responseText);
                updateTotalCartItems(json_response['total_items']);

                let cls = 'alert-success'
                let msg = json_response['msg'];
                showAlert(msg, cls, '#product-container', '#product-details');

            }
            else if (xhr.status == 401){
                json_response = JSON.parse(xhr.responseText);

                let cls = 'alert-danger'
                let msg = json_response['error'];
                showAlert(msg, cls, '#product-container', '#product-details');
            }
        }

        xhr.onerror = () => {
            console.log('Ajax request failed');
        }

        xhr.send();
    });
</script>
{% endblock %}